import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Nav
    'nav.home': 'Beranda',
    'nav.about': 'Tentang Kami',
    'nav.services': 'Layanan',
    'nav.portfolio': 'Portofolio',
    'nav.blog': 'Blog',
    'nav.careers': 'Karir',
    'nav.contact': 'Hubungi Kami',
    // Services dropdown
    'services.web': 'Web Development',
    'services.mobile': 'Mobile Development',
    'services.product': 'Product Design',
    'services.graphic': 'Design Grafis',
    // Services Detailed
    'services.web.desc': 'Kami membangun website modern, responsif, dan performa tinggi yang disesuaikan dengan kebutuhan bisnis Anda.',
    'services.web.features': 'PWA, E-commerce, Custom Dashboard, Optimization.',
    'services.mobile.desc': 'Pengembangan aplikasi native dan cross-platform dengan user experience yang mulus di iOS dan Android.',
    'services.mobile.features': 'React Native, Flutter, App Store Deployment, Maintenance.',
    'services.product.desc': 'Desain produk digital mulai dari riset pengguna hingga prototipe fungsional yang siap diproduksi.',
    'services.product.features': 'UI/UX Audit, User Research, Prototyping, Design System.',
    'services.graphic.desc': 'Identitas visual yang kuat untuk memperkuat brand awareness dan kepercayaan pelanggan Anda.',
    'services.graphic.features': 'Logo Design, Branding, Marketing Collateral, Social Media Assets.',
    // Home Page Extensions
    'home.services.title': 'Layanan Unggulan Kami',
    'home.services.desc': 'Solusi kustom yang dirancang untuk mempercepat pertumbuhan bisnis Anda di era digital.',
    'home.process.title': 'Bagaimana Kami Bekerja',
    'home.process.desc': 'Pendekatan sistematis kami memastikan setiap proyek diselesaikan tepat waktu dengan standar kualitas tertinggi.',
    'home.process.1.title': 'Discovery',
    'home.process.1.desc': 'Kami mendalami bisnis Anda untuk memahami tujuan dan tantangan unik Anda.',
    'home.process.2.title': 'Strategi',
    'home.process.2.desc': 'Menyusun peta jalan teknis dan desain yang dioptimalkan untuk hasil maksimal.',
    'home.process.3.title': 'Eksekusi',
    'home.process.3.desc': 'Pengembangan iteratif dengan transparansi penuh di setiap tahapnya.',
    // Hero
    'hero.badge': 'AGENSI BERORIENTASI MASA DEPAN',
    'hero.title': 'Arsitek Masa Depan ',
    'hero.titleAccent': 'Digital Anda.',
    'hero.desc': 'SolvingTech adalah agensi solusi digital yang menjembatani kesenjangan antara rekayasa kompleks dan desain yang berpusat pada manusia. Kami membangun infrastruktur untuk pertumbuhan yang tak terbatas.',
    'hero.ctaPrimary': 'Mulai Proyek',
    'hero.ctaSecondary': 'Pelajari Metode Kami',
    'hero.statLabel': 'PROYEK SELESAI DENGAN PRESISI',
    // Vision
    'vision.title': 'Visi & Misi Kami',
    'vision.desc': 'Membangun ekosistem teknologi yang tidak hanya berfungsi, tapi menginspirasi kemajuan berkelanjutan.',
    'vision.cardTitle': 'Visi Kami',
    'vision.cardDesc': 'Menjadi standar global dalam kemitraan teknologi, di mana inovasi bertemu dengan integritas, menciptakan solusi yang mendefinisikan ulang batas-batas kemungkinan digital bagi setiap mitra kami.',
    'vision.misiTitle': 'Misi Kami',
    'misi.1': 'Memberikan solusi rekayasa perangkat lunak yang presisi dan terukur.',
    'misi.2': 'Memprioritaskan pengalaman pengguna melalui desain yang intuitif.',
    'misi.3': 'Memberdayakan bisnis melalui integrasi AI dan data pintar.',
    'vision.quality': 'KOMITMEN KUALITAS',
    // Values
    'values.badge': 'NILAI-NILAI INTI',
    'values.title': 'Dasar Dari Setiap Keputusan Kami.',
    'values.desc': 'Budaya kami dibangun di atas prinsip-prinsip yang memastikan transparansi dan keunggulan teknis dalam setiap baris kode.',
    'values.1.title': 'Presisi Tinggi',
    'values.1.desc': 'Kami tidak percaya pada \'cukup bagus\'. Setiap detail dioptimalkan untuk performa puncak.',
    'values.2.title': 'Radikal Transparansi',
    'values.2.desc': 'Komunikasi jujur dan akses terbuka ke proses pengembangan kami untuk semua mitra.',
    'values.3.title': 'Inovasi Berani',
    'values.3.desc': 'Kami merangkul tantangan sulit yang dihindari agensi lain untuk menciptakan terobosan.',
    'values.4.title': 'Empati Desain',
    'values.4.desc': 'Memahami kebutuhan akhir pengguna adalah inti dari setiap solusi teknis yang kami buat.',
    // Team
    'team.badge': 'KEPEMIMPINAN',
    'team.title': 'Temui Para Visioner',
    'team.desc': 'Dipimpin oleh para ahli industri dengan pengalaman kolektif lebih dari 20 tahun di Silicon Valley dan Asia Tenggara.',
    // Portfolio Page
    'port.badge': 'KARYA KAMI',
    'port.title': 'Portofolio',
    'port.desc': 'Setiap produk yang kami bangun memiliki cerita yang berbeda. Kami bergabung dengan tim klien sebagai mitra teknologi untuk mengatasi tantangan dan membantu mereka tumbuh.',
    'port.cats.all': 'Semua',
    'port.cats.web': 'Pengembangan Web',
    'port.cats.mobile': 'Pengembangan Mobile',
    'port.cats.design': 'Desain UI/UX',
    'port.cats.ai': 'AI & Data',
    'port.item.cta': 'Lihat Studi Kasus',
    'port.footer.title': 'Mari bangun kisah sukses Anda selanjutnya.',
    'port.footer.desc': 'Bergabunglah dengan portofolio merek dengan pertumbuhan tinggi kami. Kami membawa keahlian teknis, Anda membawa visi.',
    'port.footer.cta': 'Mulai Proyek',
    // Blog Page
    'blog.badge': 'WAWASAN UNGGULAN',
    'blog.title': 'Masa Depan AI dalam Rekayasa Perangkat Lunak.',
    'blog.desc': 'Bagaimana kecerdasan buatan mengubah cara tim Agile berkolaborasi dan menulis kode yang lebih bersih, lebih cepat, dan lebih efisien di tahun 2024.',
    'blog.cta': 'Baca Selengkapnya',
    'blog.readTime': '8 Menit Membaca',
    'blog.cats.all': 'Semua',
    'blog.newsletter.title': 'Dapatkan Update Wawasan Terbaru.',
    'blog.newsletter.desc': 'Bergabunglah dengan 5,000+ profesional teknologi yang menerima buletin mingguan kami.',
    'blog.newsletter.placeholder': 'Alamat email Anda',
    'blog.newsletter.cta': 'Langganan Sekarang',
    // Careers Page
    'career.badge': 'GABUNG MISI KAMI',
    'career.title': 'Kami Mencari Anda! Apa yang Anda tunggu?',
    'career.desc': 'Bergabunglah dengan kami dan nikmati perjalanannya. Bergabunglah dengan tim profesional berketerampilan tinggi yang menghargai desain, kode berkualitas, dan suasana kerja yang ramah.',
    'career.cta': 'Lihat Lowongan',
    'career.culture.title': 'Budaya Kami',
    'career.culture.desc': 'Kami percaya bahwa keunggulan teknis dan lingkungan yang positif tidak saling eksklusif. Insinyur kami bekerja dalam unit yang memprioritaskan otonomi.',
    'career.stat.sat': 'Tingkat kepuasan karyawan.',
    'career.stat.train': 'Jalur pelatihan berkelanjutan.',
    'career.remote.title': 'Utamakan Remote',
    'career.remote.desc': 'Bekerja dari mana saja di dunia, didukung oleh tunjangan kantor rumah yang memadai.',
    'career.openings.title': 'Posisi Terbuka',
    'career.location': 'Karawang, West Java',
    'career.pos.mobile': 'App Mobile Engineer',
    'career.pos.software': 'Software Engineer',
    'career.pos.marketing': 'Digital Marketing',
    'career.form.title': 'Form Aplikasi Lamaran',
    'career.form.name': 'Nama Lengkap (Sesuai KTP)',
    'career.form.dob': 'Tanggal Lahir',
    'career.form.domicile': 'Domisili',
    'career.form.education': 'Pendidikan Terakhir',
    'career.form.school': 'Nama Sekolah/Universitas',
    'career.form.score': 'Nilai Akhir / IPK',
    'career.form.phone': 'Nomor HP (WhatsApp)',
    'career.form.email': 'Alamat Email',
    'career.form.position': 'Posisi yang Dilamar',
    'career.form.cv': 'Lampirkan CV (PDF)',
    'career.form.submit': 'Kirim Lamaran',
    'career.form.success': 'Lamaran Berhasil Dikirim! Kami akan menghubungi Anda segera.',
    'career.process.title': 'Proses Rekrutmen',
    'career.process.desc': 'Cepat, transparan, dan menghargai.',
    'career.process.1': 'Peninjauan',
    'career.process.1.desc': 'Ditinjau dalam 48 jam.',
    'career.process.2': 'Panggilan Awal',
    'career.process.2.desc': 'Obrolan budaya 30 menit.',
    'career.process.3': 'Tantangan',
    'career.process.3.desc': 'Tugas teknis dunia nyata.',
    'career.process.4': 'Penawaran',
    'career.process.4.desc': 'Paket penawaran kompetitif.',
    'career.cta.title': 'Tidak menemukan peran yang cocok?',
    'career.cta.desc': 'Kirimkan aplikasi terbuka. Kami selalu mencari bakat baru.',
    'career.cta.placeholder': 'Email Anda',
    // Footer
    'footer.about': 'Membawa presisi rekayasa ke dunia kreatif. Mitra digital terpercaya untuk masa depan bisnis Anda.',
    'footer.unit': 'Dibuat dengan keunggulan di Jakarta.',
    'contact.title': 'Hubungi Kami',
    'contact.desc': 'Ada proyek menarik? Mari bicarakan bagaimana kami bisa membantu mewujudkannya.',
    'contact.info.title': 'Informasi Kontak',
    'contact.address': 'Jl. Galuh Mas Raya, Karawang, Jawa Barat 41361',
    'contact.email': 'hello@solvingtech.id',
    'contact.phone': '+62 812 3456 7890',
    'contact.socials': 'Media Sosial',
    'contact.form.title': 'Kirim Pesan',
    'contact.form.name': 'Nama Anda',
    'contact.form.email': 'Alamat Email',
    'contact.form.subject': 'Subjek',
    'contact.form.message': 'Pesan Anda',
    'contact.form.send': 'Kirim Pesan Sekarang',
  },
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.careers': 'Careers',
    'nav.contact': 'Contact Us',
    // Services dropdown
    'services.web': 'Web Development',
    'services.mobile': 'Mobile Development',
    'services.product': 'Product Design',
    'services.graphic': 'Graphic Design',
    // Services Detailed
    'services.web.desc': 'We build modern, responsive, and high-performance websites tailored to your business needs.',
    'services.web.features': 'PWA, E-commerce, Custom Dashboard, Optimization.',
    'services.mobile.desc': 'Native and cross-platform app development with a seamless user experience on iOS and Android.',
    'services.mobile.features': 'React Native, Flutter, App Store Deployment, Maintenance.',
    'services.product.desc': 'Digital product design from user research to functional production-ready prototypes.',
    'services.product.features': 'UI/UX Audit, User Research, Prototyping, Design System.',
    'services.graphic.desc': 'Strong visual identity to strengthen your brand awareness and customer trust.',
    'services.graphic.features': 'Logo Design, Branding, Marketing Collateral, Social Media Assets.',
    // Home Page Extensions
    'home.services.title': 'Our Core Services',
    'home.services.desc': 'Custom solutions designed to accelerate your business growth in the digital age.',
    'home.process.title': 'How We Work',
    'home.process.desc': 'Our systematic approach ensures every project is completed on time with the highest quality standards.',
    'home.process.1.title': 'Discovery',
    'home.process.1.desc': 'We dive deep into your business to understand your unique goals and challenges.',
    'home.process.2.title': 'Strategy',
    'home.process.2.desc': 'Crafting technical and design roadmaps optimized for maximum results.',
    'home.process.3.title': 'Execution',
    'home.process.3.desc': 'Iterative development with full transparency at every stage.',
    // Hero
    'hero.badge': 'FORWARD-THINKING AGENCY',
    'hero.title': 'Architecting Your ',
    'hero.titleAccent': 'Digital Future.',
    'hero.desc': 'SolvingTech is a digital solution agency that bridges the gap between complex engineering & human-centered design. We build infrastructure for limitless growth.',
    'hero.ctaPrimary': 'Start Project',
    'hero.ctaSecondary': 'Learn Our Method',
    'hero.statLabel': 'PROJECTS FINISHED WITH PRECISION',
    // Vision
    'vision.title': 'Our Vision & Mission',
    'vision.desc': 'Building tech ecosystems that don\'t just function, but inspire sustainable progress.',
    'vision.cardTitle': 'Our Vision',
    'vision.cardDesc': 'To be the global standard in technology partnership, where innovation meets integrity, creating solutions that redefine the boundaries of digital possibilities for every partner.',
    'vision.misiTitle': 'Our Mission',
    'misi.1': 'Delivering precise and scalable software engineering solutions.',
    'misi.2': 'Prioritizing user experience through intuitive design.',
    'misi.3': 'Empowering businesses through AI integration and smart data.',
    'vision.quality': 'QUALITY COMMITMENT',
    // Values
    'values.badge': 'CORE VALUES',
    'values.title': 'The Foundation of Every Decision.',
    'values.desc': 'Our culture is built on principles that ensure transparency and technical excellence in every line of code.',
    'values.1.title': 'High Precision',
    'values.1.desc': 'We don\'t believe in \'good enough\'. Every detail is optimized for peak performance.',
    'values.2.title': 'Radical Transparency',
    'values.2.desc': 'Honest communication and open access to our development process for all partners.',
    'values.3.title': 'Bold Innovation',
    'values.3.desc': 'We embrace the hard challenges avoided by other agencies to create breakthroughs.',
    'values.4.title': 'Design Empathy',
    'values.4.desc': 'Understanding user needs is the core of every technical solution we create.',
    // Team
    'team.badge': 'LEADERSHIP',
    'team.title': 'Meet the Visionaries',
    'team.desc': 'Led by industry experts with 20+ collective years of experience in Silicon Valley and Southeast Asia.',
    // Portfolio Page
    'port.badge': 'OUR WORK',
    'port.title': 'Portfolio',
    'port.desc': 'Every product we build has a different story. We join client teams as technology partners to solve challenges and help them grow.',
    'port.cats.all': 'All',
    'port.cats.web': 'Web Development',
    'port.cats.mobile': 'Mobile Development',
    'port.cats.design': 'UI/UX Design',
    'port.cats.ai': 'AI & Data',
    'port.item.cta': 'View Case Study',
    'port.footer.title': 'Let\'s build your next success story.',
    'port.footer.desc': 'Join our high-growth brand portfolio. We bring technical expertise, you bring the vision.',
    'port.footer.cta': 'Start Project',
    // Blog Page
    'blog.badge': 'FEATURED INSIGHT',
    'blog.title': 'The Future of AI in Software Engineering.',
    'blog.desc': 'How artificial intelligence is changing the way Agile teams collaborate and write cleaner, faster, and more efficient code in 2024.',
    'blog.cta': 'Read More',
    'blog.readTime': '8 Min Read',
    'blog.cats.all': 'All',
    'blog.newsletter.title': 'Get the Latest Insight Updates.',
    'blog.newsletter.desc': 'Join 5,000+ tech professionals receiving our weekly newsletter.',
    'blog.newsletter.placeholder': 'Your email address',
    'blog.newsletter.cta': 'Subscribe Now',
    // Careers Page
    'career.badge': 'JOIN THE MISSION',
    'career.title': 'We Want You! What are you waiting for?',
    'career.desc': 'Join us and enjoy the journey. Join a team of highly skilled professionals who appreciate design, quality code, and a friendly work atmosphere.',
    'career.cta': 'View Openings',
    'career.culture.title': 'Our Culture',
    'career.culture.desc': 'We believe that technical excellence and a positive environment are not mutually exclusive. Our engineers work in pods that prioritize autonomy.',
    'career.stat.sat': 'Employee satisfaction rate.',
    'career.stat.train': 'Ongoing training paths.',
    'career.remote.title': 'Remote First',
    'career.remote.desc': 'Work from anywhere in the world, supported by a generous home-office stipend.',
    'career.openings.title': 'Open Positions',
    'career.location': 'Karawang, West Java',
    'career.pos.mobile': 'App Mobile Engineer',
    'career.pos.software': 'Software Engineer',
    'career.pos.marketing': 'Digital Marketing',
    'career.form.title': 'Job Application Form',
    'career.form.name': 'Full Name (as per ID)',
    'career.form.dob': 'Date of Birth',
    'career.form.domicile': 'Domicile',
    'career.form.education': 'Last Education',
    'career.form.school': 'School/University Name',
    'career.form.score': 'Final Grade / GPA',
    'career.form.phone': 'Phone Number (WhatsApp)',
    'career.form.email': 'Email Address',
    'career.form.position': 'Applied Position',
    'career.form.cv': 'Attach CV (PDF)',
    'career.form.submit': 'Submit Application',
    'career.form.success': 'Application Submitted Successfully! We will contact you soon.',
    'career.process.title': 'Hiring Process',
    'career.process.desc': 'Fast, transparent, and respectful.',
    'career.process.1': 'Review',
    'career.process.1.desc': 'Reviewed within 48 hours.',
    'career.process.2': 'Intro Call',
    'career.process.2.desc': '30-minute culture chat.',
    'career.process.3': 'Challenge',
    'career.process.3.desc': 'Real-world technical task.',
    'career.process.4': 'Offer',
    'career.process.4.desc': 'Competitive offer packages.',
    'career.cta.title': 'Didn\'t find the right role?',
    'career.cta.desc': 'Submit an open application. We\'re always looking for new talent.',
    'career.cta.placeholder': 'Your Email',
    // Footer
    'footer.about': 'Bringing engineering precision to the creative world. Your trusted digital partner for your business future.',
    'footer.unit': 'Made with excellence in Jakarta.',
    'contact.title': 'Contact Us',
    'contact.desc': 'Have an exciting project? Let\'s talk about how we can help make it happen.',
    'contact.info.title': 'Contact Information',
    'contact.address': 'Jl. Galuh Mas Raya, Karawang, West Java 41361',
    'contact.email': 'hello@solvingtech.id',
    'contact.phone': '+62 812 3456 7890',
    'contact.socials': 'Social Media',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message Now',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
